### PR TITLE
Improvements and a new Demo

### PR DESCRIPTION
**Pull request by joecare99**
New Feature:
Styles, 
Fonts, (partly)
Bookmarks,
Links (Hyperlinks)

### CODE REVIEW

**Comment by joecare99** [comment]
Hi, 
I fixed some mem-leaks, and added some features.

**Comment by joecare99** [comment]
Hi, here are some new improvements,

Text-Color, Headings ...
also started some documentation.

**Comment by dgaspary** [comment]
Hi.

I'll (probably) review and merge tomorrow (monday) or tuesday.

Thanks for your effort.

**Comment by dgaspary** [comment]
I have some doubts about some classes hierarchy and location of some methods(FindStyle belonging to TOdfElement)... 

If you submit something in the future, please avoid changing / commit lazarus project files. They make an unnecessary volume to the commit.

But.. the code needs a lot of refactoring anyway and all of that are just details.. 

Excelent Job with the demos. 

Thank you very much!

**Comment by joecare99** [comment]
Hi, 

I appended a method Find to be able to find named Items when the actual name is in the attributes (It can only find styles at the moment, but should be extended to whatever is needed (e.G: fonts, paragraphs, ... ) .
So for me this is a general find method.

GreetingsJ.C:
 

    On Tuesday, October 29, 2019, 11:51:50 PM GMT+1, Daniel F. Gaspary <notifications@github.com> wrote:  
 
 
I have some doubts about some classes hierarchy and location of some methods(FindStyle belonging to TOdfElement)...

If you submit something in the future, please avoid changing / commit lazarus project files. They make a unnecessary volume to the commit.

But.. the code needs a lot of refactoring anyway and all of that are just details..

Excelent Job with the demos.

Thank you very much!

**Comment by joecare99** [comment]
Hi again,
About the project files:This was not by accident.If you want a more secure system. You have to strictly separate the binaries and compiler-Outputs from the source. And also separate the data-files from the source.e.G: On my system, user-writable directories are not allowed to execute files. Only the compiler is allowed to write into the binary-folder. So the system is more robust against ransomware- and other attacks.
On the downside, all data that is handled by the executable has to be outside the binary-folder. If you want to be Win 7++ compatible you have to do that anyway.So I (had to) change(d) the filesystem to compile to ..\..\bin\XXX for that folder has executable but only user-readable attributes, and change the data-folder to ..\..\output. 

On the upside, you can safely erase all files in ..\..\bin because these will be build again on compile. You can safely distribute/archive your code by handling the source-folders, 
because everything that is needed to compile is there.

On my system, I also separate the project-files from the source-files, because I have project-files for different Delphi-Versions and one additional for FPC. All of these compile the same source-code.So these project files have to be in separate directories because these are (mostly) not compatible with each other.
Best regardsJ.C.
    On Wednesday, October 30, 2019, 2:56:21 PM GMT+1, Joe Care <joe_care_99@yahoo.com> wrote:  
 
  Hi, 

I appended a method Find to be able to find named Items when the actual name is in the attributes (It can only find styles at the moment, but should be extended to whatever is needed (e.G: fonts, paragraphs, ... ) .
So for me this is a general find method.

GreetingsJ.C:
 

    On Tuesday, October 29, 2019, 11:51:50 PM GMT+1, Daniel F. Gaspary <notifications@github.com> wrote:  
 
 
I have some doubts about some classes hierarchy and location of some methods(FindStyle belonging to TOdfElement)...

If you submit something in the future, please avoid changing / commit lazarus project files. They make a unnecessary volume to the commit.

But.. the code needs a lot of refactoring anyway and all of that are just details..

Excelent Job with the demos.

Thank you very much!

**Pull request merged**
